# Generated by Django 4.2.18 on 2025-07-08 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('tag', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('clan_level', models.IntegerField()),
                ('clan_points', models.IntegerField()),
                ('members_count', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('tag', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('exp_level', models.IntegerField()),
                ('trophies', models.IntegerField()),
                ('donations', models.IntegerField()),
                ('donations_received', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('clan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='clan_stats.clan')),
            ],
        ),
    ]
