# Generated by Django 4.2.18 on 2025-07-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan_stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='archer_queen_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='barbarian_king_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='details_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='grand_warden_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='royal_champion_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='town_hall_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
